[book]
authors = ["anete.anetes"]
language = "ru"
multilingual = false
src = "src"
title = "World of Warcraft The Roreplay Game 2d Edition - Русскоязычная адаптация"

[output.html]
default-theme = "rust"
additional-css = ["./theme/css/plates.css"]